version: 0.2
phases:
  install:
    commands:
      - pip install awscli --upgrade
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged.yml
artifacts:
  files:
    - packaged.yml
    - prod-configuration.json