version: 0.2
phases:
  install:
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update && apt-get install -y yarn
  pre_build:
    commands:
      - yarn install --frozen-lockfile
      - yarn run dev:env --stack-name $STACK_NAME --live
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - aws s3 sync --delete dist/ "s3://${SITE_BUCKET}"