Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AliasAttributes: ['email']
      AutoVerifiedAttributes: ['email']
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      Schema:
        - {
          Name: email,
          Required: true
        }
        - {
          Name: given_name,
          Required: true
        }
  WebUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      GenerateSecret: false
      UserPoolId: !Ref UserPool
Outputs:
  userPoolId:
    Description: User Pool ID
    Value: !Ref UserPool
  clientId:
    Description: User Pool Web Client ID
    Value: !Ref WebUserPoolClient